[package]
name = "logger-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
hostname = "^0.4"
users = "0.11"
ctrlc = "3.4"
clap = { version = "4.5.18", features = ["derive"] }
